# Generated by Django 2.0.3 on 2018-03-08 19:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('fine_collected', models.IntegerField()),
                ('totalFine', models.IntegerField(default=0)),
                ('timeOfIssue', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('challanIssued', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('inspectorId', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('fine', models.IntegerField()),
                ('vehicleTaken', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ViolationToChallan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ControlSystem.Challan')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ControlSystem.Violation')),
            ],
        ),
        migrations.AddField(
            model_name='duty',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='duties_done_by', to='ControlSystem.Inspector'),
        ),
        migrations.AddField(
            model_name='duty',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='duty_done_at', to='ControlSystem.Location'),
        ),
        migrations.AddField(
            model_name='challan',
            name='issuedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issued_by', to='ControlSystem.Inspector'),
        ),
        migrations.AddField(
            model_name='challan',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challan_issued_at', to='ControlSystem.Location'),
        ),
        migrations.AddField(
            model_name='challan',
            name='violations',
            field=models.ManyToManyField(through='ControlSystem.ViolationToChallan', to='ControlSystem.Violation'),
        ),
        migrations.AlterUniqueTogether(
            name='violationtochallan',
            unique_together={('challan', 'violation')},
        ),
    ]
